spring.application.name=BackMed

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/BackMed
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
spring.secretKey=BackMed@SecretKey2025
spring.emissor=BackMed
spring.tempoExpiracao=120
